# syntax=docker/dockerfile:1

FROM golang:1.21-alpine

WORKDIR /app

RUN apk add build-base

COPY go.mod ./
COPY go.sum ./

RUN go mod download
# RUN go get github.com/mattn/go-sqlite3

COPY *.go ./
COPY public ./public
# COPY art.db ./

RUN go build -o /weathersrv

EXPOSE 1323

CMD [ "/weathersrv" ]